In [3]:
import numpy as np

In [5]:
# Create 1D array with integers from 1 to 20
array_1 = np.arange(0,21)
array_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [7]:
sum_ = np.sum(array_1)
mean_ = np.mean(array_1)
median_ = np.median(array_1)
std_dev = np.std(array_1)

print("Array:", array_1)
print("Sum:", sum_)
print("Mean:", mean_)
print("Median:", median_)
print("Standard Deviation:", std_dev)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.0
Median: 10.0
Standard Deviation: 6.0553007081949835


In [9]:
# b. Indices of elements greater than 10
indices = np.where(array_1 > 10)
print("Indices of elements > 10:", indices[0])

Indices of elements > 10: [11 12 13 14 15 16 17 18 19 20]


In [11]:
# Create 2D array of shape 4x4 with values 1 to 16
array_2 = np.arange(1, 17).reshape(4, 4)
array_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [13]:
# b. Transpose
transpose = array_2.T
print("Transpose:\n", transpose)

Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [15]:
# c. Row-wise and Column-wise sums
row_sums = np.sum(array_2, axis=1)
col_sums = np.sum(array_2, axis=0)

print("Row-wise Sums:", row_sums)
print("Column-wise Sums:", col_sums)

Row-wise Sums: [10 26 42 58]
Column-wise Sums: [28 32 36 40]


In [17]:
# Create two 3x3 arrays with random integers between 1 and 20
np.random.seed(0)  # for reproducibility
array_a = np.random.randint(1, 21, size=(3, 3))
array_b = np.random.randint(1, 21, size=(3, 3))

print("Array A:\n", array_a)
print("Array B:\n", array_b)

Array A:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]
Array B:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]


In [19]:
# a. Element-wise addition, subtraction, multiplication
add = array_a + array_b
sub = array_a - array_b
mul = array_a * array_b

print("Addition:\n", add)
print("Subtraction:\n", sub)
print("Multiplication:\n", mul)

Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]
Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]
Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]


In [21]:
# b. Dot product
dot_product = np.dot(array_a, array_b)
print("Dot Product:\n", dot_product)

Dot Product:
 [[112 221 303]
 [148 200 132]
 [375 552 404]]


In [23]:
# Create 1D array of size 12
array_1d_12 = np.arange(1, 13)

# Reshape into 3x4
reshaped_array = array_1d_12.reshape(3, 4)
print("Reshaped Array (3x4):\n", reshaped_array)

# Slice: first two rows and last two columns
sliced = reshaped_array[:2, -2:]
print("Sliced (first 2 rows, last 2 columns):\n", sliced)

Reshaped Array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
